config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'entries#index'
  resources :entries do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :subhead, length: {maximum: 200}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.entry_id = params[:entry_id]
    @comment.save
    redirect_to entry_path(@comment.entry_id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to comments_path(@comment)
    flash.notice = "Noticia '#{@comment.titulo}' fue actualizada con exito!"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  include EntriesHelper

  def index
    @entries = Entry.order(created_at: :desc).limit(10)
    @entries.each do |entry|
      if entry.body.length >= 500
        #find last space
        last_space = entry.body[0..500].rindex(' ') - 1
        entry.body = entry.body[0..last_space] + '...'
      end

  end
  end

  def show
    @entry = Entry.find(params[:id])
    @comment = Comment.new
    @comment.entry_id = @entry.id
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entry_path(@entry)
    else
      render 'new'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_path
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      redirect_to entries_path(@entry)
      flash.notice = "Noticia '#{@entry.title}' fue actualizada con exito!"
    else
      render 'edit'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
     redirect_to entries_path
    end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
  
end

app/helpers/entries_helper.rb
module EntriesHelper

  def entry_params
    params.require(:entry).permit(:title, :subhead, :body)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<div class="panel panel-default" style="width:1200px; margin-top:10px;
margin-left: auto; margin-right: auto">
<div class="panel-heading">
  <h3>Escribe un Comentario</h3>
</div>
<p>
  <div style="text-align: justify; margin: 20px">
  <%= bootstrap_form_for [ @entry, @comment ] do |f| %>
    <p>
      <%= f.text_field :author_name %>
    </p>
    <p>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit 'Submit' %>
    </p>
  <% end %>
</div>
</p>
</div>

app/views/entries/_comment.html.erb
<div class="panel panel-default" style="width:1200px; margin-top:50px;
margin-left: auto; margin-right: auto">
  <div class="panel-heading">
    <h2>Comentarios (<%= @entry.comments.size %>)</h2>
  </div>
  <div style="text-align: justify; margin: 20px">
    <h4>Comentado por: <%= comment.author_name %></h4>
    <p class="comment">Mensaje: <%= comment.body %></p>
  </div>
</div>

app/views/entries/_form.html.erb
<div style="width:650px; margin-top:100px; margin-left: auto; margin-right: auto">
  <%= bootstrap_form_for(@entry) do |f| %>

  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %> prohibited
        this entry from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <ul>
    <% @entry.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
    <p>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.text_area :subhead %>
    </p>
    <p>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
  <p>
  <%= button_to 'Volver', entries_path, :method => "get",
    class: "btn btn-primary" %>
  </p>
</div>

app/views/entries/edit.html.erb
<h1>Editar una Noticia</h1>
<%= render partial: 'form' %>

app/views/entries/index.html.erb
<h1>Noticias</h1>

<ul id="entries">
  <% @entries.each do |entry| %>
    <li>
      <div class="panel panel-default" style="width:1200px; margin-top:50px;
      margin-left: auto; margin-right: auto">

        <div class="panel-heading">
          <h2><%= link_to entry.title, entry_path(entry),
          class: 'entry_title', id: "entry_#{entry.id}" %></h2>
          <h6> Fecha de Publicación: <%= entry.created_at.strftime("%H:%M:%S - %d/%m/%Y")%></h6>
        </div>

        <div style="text-align: justify; margin: 20px">
          <%= entry.subhead %>
        </div>

        <div style="text-align: justify; margin: 20px">
          <%= entry.body %>
        </div>

      </div>
    </li>
  <% end %>
</ul>

<div style = "margin-left: 140px; margin-top:50px;">
  <%= button_to "Crear Nueva Noticia", new_entry_path, class: "btn btn-primary",
  :method => "get" %>
</div>

app/views/entries/new.html.erb
<h1>Crear una Nueva Noticia</h1>

<%= render partial: 'form' %>

app/views/entries/show.html.erb
<div class="panel panel-default" style="width:1200px; margin-top:50px;
margin-left: auto; margin-right: auto">

  <div class="panel-heading">
    <h2><%= @entry.title %></h2>
    <h6> Fecha de Publicación: <%= @entry.created_at.strftime("%H:%M:%S - %d/%m/%Y")%></h6>
  </div>

  <div id ="wrapper_show">


      <div style="text-align: justify; margin: 20px">
        <%= @entry.subhead %>
      </div>



      <div style="text-align: justify; margin: 20px">
        <%= @entry.body %>
      </div>


  </div>

  <div style="margin-left: 20px">
    <p>
    <%= button_to "Editar Noticia", edit_entry_path(@entry),
    class: "btn btn-primary", :method => "get"%>
    </p>
    <p>
    <%= button_to "Borrar Noticia", entry_path(@entry),
      class: "btn btn-primary", method: :delete,
        data: {confirm: "¿Seguro que quieres borrar esta Noticia?"}%>
    </p>
    <p>
    <%= button_to 'Volver', entries_path, :method => "get",
      class: "btn btn-primary" %>
    </p>
  </div>

</div>



<%= render partial: 'comments/form' %>
<%= render partial: 'entries/comment', collection: @entry.comments.reverse %>

app/views/home/index.html.erb
<h1>TAREA 1</h1>
<h2> Tomás Godoy </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="css/custom.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">


  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary'  %>
  <% else %>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
    <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary'  %>
  <% end %>
  </p>


  <body>
    <%= yield %>
  </body>
</html>